Hangman minigame code
TechnoVisionDev/TechnoBot pull request #41
Opened 2021-01-05 09:27 UTC by adex720

This worked on my own bot so should work here too. words.json should be moved somewhere else and it's path updated in WordList.java at row 20.

2021-01-05 09:38 UTC, Sparky200 requested changes
Looking good, just needs a few edits!

2021-01-05 09:38 UTC, Sparky200 commented on src/main/java/com/technovision/technobot/util/minigames/WordList.java
> +            Object obj = new JSONParser().parse(new FileReader("C:\\Users\\adex\\Desktop\\AdexBot\\src\\main\\resources\\words.json"));      //Change this
Don't hardcode file references.

2021-01-05 09:38 UTC, Sparky200 commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    public void finish() {
Shouldn't this method remove the game from the games list?

2021-01-05 09:38 UTC, Sparky200 commented on src/main/java/com/technovision/technobot/commands/fun/CommandHangmanStart.java
> +        super(bot, "start hangman", "Start a game of hangman", "{prefix}start hangman", Command.Category.FUN);
This is not executable with that name.

2021-01-05 09:44 UTC, TheOnlyTails requested changes
Looks good. Just fix what Sparky and I pointed out.

2021-01-05 09:44 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandHangmanGuess.java
> +         String messageContent = event.getMessage().getContentRaw();
Can you add a check here to make sure a game is in progress?

2021-01-05 09:44 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    public static final HashMap<TextChannel, Hangman> GAMES = new HashMap<>();
Don't associate the game with a channel, associate it with a user. We want all games to be played in the bot commands channel.

2021-01-05 09:44 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +            channel.sendMessage("This channel already has a game of Hangman on.").queue();
Remove this check and just reset the game for the user.

2021-01-05 09:44 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    public void reduceLive() {
there's no need for this method. Just use `livesLeft--` and add a comment.

2021-01-05 09:44 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +        Collections.sort(guessed);
there's no need for this method. Just use `guessed.sorted()` and add a comment.

2021-01-05 09:44 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/util/minigames/WordList.java
> +            Object obj = new JSONParser().parse(new FileReader("C:\\Users\\adex\\Desktop\\AdexBot\\src\\main\\resources\\words.json"));      //Change this
this is very bad. Never use a hard coded file path on a community project.

2021-01-05 09:44 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandHangmanStart.java
> +        super(bot, "start hangman", "Start a game of hangman", "{prefix}start hangman", Command.Category.FUN);
Yep. Change this to a one word abbriviation.

2021-01-05 09:44 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandHangmanStart.java
> +        super(bot, "start-hangman", "Start a game of hangman", "{prefix}start-hangman", Command.Category.FUN);
no. Use a one word abbreviation.

2021-01-05 09:49 UTC, adex720 commented on src/main/java/com/technovision/technobot/commands/fun/CommandHangmanGuess.java
> +         String messageContent = event.getMessage().getContentRaw();
It is the first if in Hangman#guess

2021-01-05 10:02 UTC, TheOnlyTails requested changes
Umm.... That's just one thing.

2021-01-05 10:03 UTC, adex720 commented
Im working on them now, just haven't updated this

2021-01-05 10:13 UTC, TheOnlyTails reviewed
Looks good!

2021-01-05 10:13 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +        Collections.sort(this.guessed);
You do know you can just do `this.guessed.sorted()`, right?

2021-01-05 10:15 UTC, adex720 commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +        Collections.sort(this.guessed);
only stream().sorted() exsists. It seemsit returns a new sorted list but leaves the original as it was.

2021-01-05 10:16 UTC, Sparky200 commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +        Collections.sort(this.guessed);
Then it's as simple as `this.guessed = this.guessed.stream().sorted()`.

2021-01-05 10:16 UTC, adex720 commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +        Collections.sort(this.guessed);
Tested it doesn't change the original. I think Collections.sort(this.guessed); is just cleaner than this.guessed = this.guessed.stream().sorted();

2021-01-05 10:24 UTC, adex720 commented
I'm struggling to find a good way to soft code the paths. Is this one good or what should I use
ClassLoader cl = Thread.currentThread().getContextClassLoader();
URL url = cl.getResource("");

2021-01-05 10:42 UTC, Sparky200 commented
21 commits :o

2021-01-05 10:44 UTC, adex720 commented
I'll done for now, gonna take a break, just add here if I have to change/add something.

2021-01-05 10:48 UTC, Sparky200 commented on src/main/java/com/technovision/technobot/util/minigames/WordList.java
> +            Object obj = new JSONParser().parse(new FileReader("C:\\Users\\adex\\Desktop\\AdexBot\\src\\main\\resources\\words.json"));      //Change this
I know you're already fixing this, but I want to quickly add onto this 😃
This reads from the uncompiled resources directory, meaning that it doesn't use the resource compiled into the JAR.
Just wanted to let you know if you ever use resources again 😉 

Also, org.json allows you to simply do `new JSONObject("{}");` :D

2021-01-05 15:07 UTC, xf8b commented on src/main/java/com/technovision/technobot/commands/fun/CommandHangmanGuess.java
> +        super(bot, "guess", "Guess something in a game of hangman", "{prefix}g   ", Command.Category.OTHER);
spaces 🤔

2021-01-05 15:08 UTC, xf8b commented on src/main/java/com/technovision/technobot/commands/fun/CommandHangmanGuess.java
> +            }
you can just substring (or skip this idk if java has skip)

2021-01-05 15:09 UTC, xf8b commented on src/main/java/com/technovision/technobot/commands/fun/CommandHangmanGuess.java
> +            Hangman.guess(event.getTextChannel(), event.getAuthor() , guess.toLowerCase);
toLowerCase is a method

2021-01-05 15:10 UTC, xf8b commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    private final User user;
arent u not supposed to use user instances and rather use the id

2021-01-05 15:22 UTC, Sparky200 commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    private final User user;
Users are cached by JDA and shouldn't change, so it would require testing. I usually use Guild IDs for anything that's being accessed multiple times by different sources, however.

2021-01-05 15:29 UTC, adex720 commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    private final User user;
It works fine with 2 games at same time and one lost game isn't affecting that much.

2021-01-05 15:32 UTC, Sparky200 commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    private final User user;
That's not what the review was. He was asking whether you're supposed to cache user IDs instead of User objects.

2021-01-05 15:33 UTC, adex720 commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    private final User user;
oh my bad. I was little confused about that tbh

2021-01-05 16:10 UTC, xf8b commented on src/main/java/com/technovision/technobot/commands/fun/CommandHangmanGuess.java
> +            String guess = event.getMessage().getContentRaw().substring(3);  //  !g e -> e
shouldnt this be 2 if you want the third character

2021-01-05 16:10 UTC, xf8b commented on src/main/java/com/technovision/technobot/commands/fun/CommandHangmanGuess.java
> +            String guess = event.getMessage().getContentRaw().substring(3);  //  !g e -> e
and on

2021-01-05 16:11 UTC, adex720 commented on src/main/java/com/technovision/technobot/commands/fun/CommandHangmanGuess.java
> +            String guess = event.getMessage().getContentRaw().substring(3);  //  !g e -> e
!=0 g=1 =2 e=e

2021-01-05 16:12 UTC, xf8b commented on src/main/java/com/technovision/technobot/util/minigames/WordList.java
> +        return words.get(new Random().nextInt(words.size()));
can use ThreadLocalRandom here

2021-01-05 16:12 UTC, xf8b commented on src/main/java/com/technovision/technobot/commands/fun/CommandHangmanGuess.java
> +            String guess = event.getMessage().getContentRaw().substring(3);  //  !g e -> e
ah ok

2021-01-05 16:13 UTC, xf8b commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    public static final HashMap<User, Hangman> GAMES = new HashMap<>();
havent changed the type of this yet

2021-01-05 16:13 UTC, xf8b commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    private final String userID;
whats the point of this

2021-01-05 16:14 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    public static final HashMap<User, Hangman> GAMES = new HashMap<>();
Just to make sure - you want him to use `Long` instead of `User` so he stores the user ID instead?

2021-01-05 16:14 UTC, xf8b commented on src/main/java/com/technovision/technobot/util/minigames/words.json
> +{
shouldnt this be in resources

2021-01-05 16:15 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/util/minigames/words.json
> +{
Yep. @adex720 please move this to the ~/data folder.

2021-01-05 16:15 UTC, xf8b commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    public static final HashMap<User, Hangman> GAMES = new HashMap<>();
ok

2021-01-05 16:16 UTC, adex720 commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    public static final HashMap<User, Hangman> GAMES = new HashMap<>();
Actually had, just forgot to replace when copied the code (thx)

2021-01-05 16:16 UTC, adex720 commented on src/main/java/com/technovision/technobot/util/minigames/words.json
> +{
Yes but I can't find the resources folder.

2021-01-05 16:20 UTC, xf8b commented on src/main/java/com/technovision/technobot/util/minigames/words.json
> +{
create it then

2021-01-05 16:21 UTC, xf8b commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    public static final HashMap<String, Hangman> GAMES = new HashMap<>();
isnt id a long or something

2021-01-05 16:21 UTC, xf8b commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    public static final HashMap<String, Hangman> GAMES = new HashMap<>();
should probably add github actions build

2021-01-05 16:22 UTC, adex720 commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    public static final HashMap<String, Hangman> GAMES = new HashMap<>();
it can be used as String or Long

2021-01-05 17:16 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    public static final HashMap<String, Hangman> GAMES = new HashMap<>();
Do a long. that way you don't need to parse it and deal with all of the exceptions and stuff.

2021-01-05 17:17 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/util/minigames/words.json
> +{
No - don't create it. You need to write code to generate it. Look at how ecomony.json` is created in code.

2021-01-05 17:18 UTC, Sparky200 commented on src/main/java/com/technovision/technobot/util/minigames/words.json
> +{
See usage [here](https://github.com/TechnoVisionDev/TechnoBot/blob/master/src/main/java/com/technovision/technobot/TechnoBot.java#L53).

2021-01-05 17:58 UTC, adex720 commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    private final String userID;
Id is used for managing which games are active/who is playing it. Name is used when bot sends message.

2021-01-05 18:03 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    private final String userID;
If you have the user, you can just get its name and ID from it. No need for an additional field.

2021-01-05 18:06 UTC, adex720 commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    private final String userID;
Didn't someone tell me to use user id instead of user?

2021-01-05 18:15 UTC, Sparky200 commented on src/main/java/com/technovision/technobot/util/minigames/Hangman.java
> +    private final String userID;
For comparing users, it's safer just in case JDA does something. Otherwise, you're free to cache. Also, make sure this is restart-friendly. This should be able to recreate the games after the bot restarts if the games didn't end.

2021-01-05 19:16 UTC, adex720 commented
wtf is this
java.lang.ClassCastException: class org.json.simple.JSONObject cannot be cast to class org.json.simple.JSONObject (org.json.simple.JSONObject and org.json.simple.JSONObject are in unnamed module of loader 'app')
	at com.adex.adexbot.minigames.hangman.Hangman.load(Hangman.java:193)
	at com.adex.adexbot.Main.main(Main.java:45)

2021-01-05 19:20 UTC, Sparky200 commented
> wtf is this
> 
> java.lang.ClassCastException: class org.json.simple.JSONObject cannot be cast to class org.json.simple.JSONObject (org.json.simple.JSONObject and org.json.simple.JSONObject are in unnamed module of loader 'app')
> 
> 	at com.adex.adexbot.minigames.hangman.Hangman.load(Hangman.java:193)
> 
> 	at com.adex.adexbot.Main.main(Main.java:45)

That's what we call an error, otherwise known as an exception.

2021-01-05 19:51 UTC, adex720 commented
Is everything now done?

2021-01-05 22:36 UTC, hirshi001 commented
Couple of suggestions. Instead of using an arraylist for the guessed characters, you should use a Set (HashSet). If you want it to be sorted, you could use a TreeSet instead.
In the static method in hangman.java, public static void startGame(...), GAMES.remove(userId) is not needed since it will be overwritten anyways later when you do GAMES.put(userId, new Hangman(user));

2021-01-06 07:58 UTC, adex720 commented
> Couple of suggestions. Instead of using an arraylist for the guessed characters, you should use a Set (HashSet). If you want it to be sorted, you could use a TreeSet instead.
> In the static method in hangman.java, public static void startGame(...), GAMES.remove(userId) is not needed since it will be overwritten anyways later when you do GAMES.put(userId, new Hangman(user));

After a bit of research and testing it seems that SortedSet is the best to choose.

2021-01-06 09:34 UTC, TheOnlyTails commented
@adex720 can you set up a test bot and check if it works?

2021-01-06 21:06 UTC, merged