RockPaperScissorsCommand
TechnoVisionDev/TechnoBot pull request #43
Opened 2021-01-05 21:59 UTC by hirshi001

Honestly if you don't want to add it, I don't mind. I think right now its just the basics.
I added a new dependency for JDA utilities, might want to check that first to make sure everything else is in check.
I haven't actually added the command to the Registry, but that would take like two seconds. I was also thinking of making it an economy command where you can gamble money, but maybe do that later.

2021-01-05 22:01 UTC, hirshi001 commented
Also, i mainly say check the dependency because I don't really know how maven works. I also haven't tested this yet.

2021-01-05 22:45 UTC, TheOnlyTails requested changes
The mechanic is fine, but some serious changes need to be made.

2021-01-05 22:45 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +    private EventWaiter ew;
`ew` is not a suitable name. Use something more descriptive, like `eventWaiter`.

2021-01-05 22:45 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        bot.getJDA().addEventListener(ew);
That's not how it works. The bot is already listening to the command just by adding it to `CommandRegistry`. Just use the `event` parameter in `execute`.

2021-01-05 22:45 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        if(players.contains(userId)) return false;
Like, are spaces not a thing?

2021-01-05 22:45 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        final int systemChoice = (int)(Math.random()*3)+1; //1=rock, 2=paper, 0=3=scissors
Please use `ThreadLocalRandom` for uniformity.

2021-01-05 22:45 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        ew.waitForEvent(MessageReceivedEvent.class, messageReceivedEvent -> players.contains(event.getAuthor().getIdLong()) && channelId==messageReceivedEvent.getChannel().getIdLong(),
Make another command for this, that takes in the guess.

2021-01-05 22:45 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +     * returns 0 if tie, 1 if player wins, -1 if player loses
If so, just use a boolean.

2021-01-05 22:45 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +    private int test(int playerChoice, int systemChoice){
This is a bad name. Just do something like `result` instead.

2021-01-05 22:45 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +    private String output(int val){
Replace this entire method with just the mechanic for ending the game. And call it something like `endGame`.

2021-01-05 22:45 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +public class CommandRockPaperScissors extends Command {
You didn't register the command, so this is worthless.

2021-01-05 22:53 UTC, xf8b commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +    private EventWaiter ew;
also not final

2021-01-05 22:53 UTC, xf8b commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +    private Set<Long> players = new HashSet<>();
not immutable

2021-01-05 22:55 UTC, hirshi001 commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +     * returns 0 if tie, 1 if player wins, -1 if player loses
boolean can only have 2 states, i need 3 for this

2021-01-05 22:56 UTC, hirshi001 commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +public class CommandRockPaperScissors extends Command {
yeah i mentioned i didn't register it i think. Mainly cause i didn't know if it would interfere with other people tryna add commands as well. Not good with github.

2021-01-05 22:56 UTC, xf8b commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        bot.getJDA().addEventListener(ew);
this is waiting for user response

2021-01-05 22:56 UTC, hirshi001 commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +    private Set<Long> players = new HashSet<>();
can you please elaborate on what you mean by this?

2021-01-05 22:57 UTC, xf8b commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +    private Set<Long> players = new HashSet<>();
the field is not final

2021-01-05 23:00 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        bot.getJDA().addEventListener(ew);
I know, but it can interfere with convos if it's waiting for user response without a command. A command is just safer.

2021-01-05 23:01 UTC, hirshi001 commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        bot.getJDA().addEventListener(ew);
I need to add the event listener separately from the command, since the execute method is only called when someone types in {prefix}rps (!rps).

2021-01-05 23:01 UTC, hirshi001 commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        if(players.contains(userId)) return false;
spaces?

2021-01-05 23:03 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        bot.getJDA().addEventListener(ew);
That's the point - add a separate command for the response.

2021-01-05 23:03 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        if(players.contains(userId)) return false;
You left out a space after the `if`.

2021-01-05 23:04 UTC, Sparky200 commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        if(players.contains(userId)) return false;
It really doesn't matter that much...

2021-01-05 23:05 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +public class CommandRockPaperScissors extends Command {
This is an open source project. If this was interfering with something, you would see that in the code, or we will tell you in the PR. Just make sure the cide works.

2021-01-05 23:06 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        if(players.contains(userId)) return false;
Good syntax matters.

2021-01-05 23:07 UTC, Sparky200 commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        if(players.contains(userId)) return false;
It's not syntax, its a space.... It really isn't that much of a bother.

2021-01-05 23:08 UTC, xf8b commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        if(players.contains(userId)) return false;
i think you mean code formatting

2021-01-05 23:13 UTC, hirshi001 commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        if(players.contains(userId)) return false;
honestly he is right. Althought it isn't much of a bother, the small things also count.

2021-01-05 23:14 UTC, hirshi001 commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        ew.waitForEvent(MessageReceivedEvent.class, messageReceivedEvent -> players.contains(event.getAuthor().getIdLong()) && channelId==messageReceivedEvent.getChannel().getIdLong(),
Alright I'll do that. I guess we can remove JDA-utilities from the dependencies

2021-01-05 23:14 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        if(players.contains(userId)) return false;
Plus, it only takes one keyboard shortcut to fix. No big deal, just to make the code prettier.

2021-01-05 23:16 UTC, xf8b commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        if(players.contains(userId)) return false;
ctrl alt L

2021-01-05 23:22 UTC, hirshi001 commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        bot.getJDA().addEventListener(ew);
actually I would rather not add it as a command since it would show up in when the help command is called. I wouldn't consider it to be its own separate command.

2021-01-05 23:26 UTC, hirshi001 commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        bot.getJDA().addEventListener(ew);
or maybe not, give me some time to rethink this

2021-01-05 23:29 UTC, TheOnlyTails commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        bot.getJDA().addEventListener(ew);
Always prioritize usability over asthetics, at least in my opinion. If something is pretty but difficult and annoying to use, it's not worth it.

2021-01-06 02:37 UTC, hirshi001 commented on src/main/java/com/technovision/technobot/commands/fun/CommandRockPaperScissors.java
> +        bot.getJDA().addEventListener(ew);
> I know, but it can interfere with convos if it's waiting for user response without a command. A command is just safer.

If your using a bot command, it really wouldn't interfere with conversations. Sure, its safer, but I don't think people would want to type a command just to respond to another one. Im thinking of changing it so the user types in their choice (rock paper or scissors) in the original command, and not having them do it later. What do you think?

2021-01-06 06:47 UTC, hirshi001 commented
Alright i have finished with the command. I threw out the part where the bot waits for the user to type out their response and instead included it as an argument, since there really wasn't a reason to do so.

2021-01-06 09:27 UTC, merged

2021-01-06 21:11 UTC, TheOnlyTails commented
@hirshi001 How are you supposed to start a game?

2021-01-06 21:26 UTC, hirshi001 commented
> @hirshi001 How are you supposed to start a game?

I forgot to add the line to send the message embed. I have just added it but I don't think it will update in the bot.

2021-01-06 21:27 UTC, hirshi001 commented
I supposed ill create another pull request

2021-01-06 21:27 UTC, TheOnlyTails commented
No. do you understand what you did? You said "Alright i have finished with the command.", without actually finishing, thus breaking the bot.
Fix this. Now.

2021-01-06 21:28 UTC, hirshi001 commented
what do you mean no? Do you not want me to fix it or what?

2021-01-06 21:29 UTC, TheOnlyTails commented
FIX THIS. NOW.